### PR TITLE
Move object conversion into response object

### PR DESCRIPTION
**Pull request by oliemansm**

### CODE REVIEW

**Comment by oliemansm** [comment]
@1096kc @ashu-walmart
I've moved the Jackson conversion inside the `GraphQLResponse` now. Some breaking changes in here, so make sure to double check if this works for you too this way.

**Comment by 1096kc** [comment]
> @1096kc @ashu-walmart
> I've moved the Jackson conversion inside the `GraphQLResponse` now. Some breaking changes in here, so make sure to double check if this works for you too this way.

@oliemansm  Thank you so much for your help! I verified that the new changes work perfectly for us. Can we make a new release that includes all the recent changes?

**Comment by oliemansm** [comment]
@1096kc Version 11.0.0 has been released just now.

**Comment by oliemansm** [comment]
@1096kc Released [version 1.0.0](https://github.com/graphql-java-kickstart/graphql-spring-webclient/releases/tag/v1.0.0)

**Pull request merged**
